// <auto-generated />
namespace TDR.Core.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class geolocationcoodinate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(geolocationcoodinate));
        
        string IMigrationMetadata.Id
        {
            get { return "201310011555510_geolocationcoodinate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
