// <auto-generated />
namespace TDR.Core.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addvalidationatrributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addvalidationatrributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201310011353058_addvalidationatrributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
